package main

const (
	// canaryFileName is the file name of the file that will act as a canary.
	canaryFileName = "important_literature.txt"
	// canaryDocument is the content of the canary file.
	canaryDocument = `=== DO NOT EDIT THIS FILE ===
Reading archival material, electronically or otherwise, is very different from reading other books.
The lack of context can be disorienting.
You can often find a copyright date, but otherwise, there's very little information about the author, the piece's publication historya, the culture at the time it ws published, or its critical reception.
In some cases, it may be impossible to even figure out who had translated works into English.
=== DO NOT EDIT THIS FILE ===`
)
